"""Initial migration

Revision ID: 878b16d1d2ff
Revises: 
Create Date: 2025-05-21 00:44:25.371721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878b16d1d2ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('upload_date')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
